In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
ar1 = np.array([1, 2, 3])
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ar1)
print(ar2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [5]:
print(ar1.shape)
print(ar2.shape)

(3,)
(2, 3)


In [6]:
ar2.shape = (6,1)
print(ar2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
